# Generated by Django 5.2 on 2025-04-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerhub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='status',
            new_name='is_finished',
        ),
        migrations.AddField(
            model_name='timer',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wipecounter',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
