# Generated by Django 5.2 on 2025-04-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerhub', '0002_rename_status_run_is_finished_timer_is_finished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='mode',
            field=models.CharField(choices=[('SPEEDRUN', 'Speedrun'), ('WIPECOUNTER', 'Wipe Counter')], max_length=30),
        ),
    ]
