# Generated by Django 5.2 on 2025-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerhub', '0003_alter_run_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='moderator_session_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='session_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
