# Generated by Django 5.2 on 2025-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerhub', '0005_game_alter_run_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
