# Generated by Django 5.2 on 2025-05-16 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerhub', '0006_run_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='moderator_session_code',
        ),
        migrations.RemoveField(
            model_name='run',
            name='session_code',
        ),
    ]
